# Node docker image on which this would be run
image: node:10

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy_production
  - api_production_test
  - publish_report

run_unit_tests:
  stage: test
  script:
    - npm install
    - npm run test

deploy_to_heroku:
  image: ruby:latest
  stage: deploy_production
  only:
    - master
    - main
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

postman_api_tests:
  stage: api_production_test
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - npm install -g newman-reporter-html
    - newman run Heroku.postman_collection.json --reporters cli,html,junit --reporter-html-export newman/report.html --reporter-junit-export report.xml
  artifacts:
    when: always
    paths:
      - newman/
    reports:
      junit: newman/report.xml

publish_api_reports:
  stage: publish_report
  script:
    - mkdir public
    - mv newman/report.html public/index.html
  artifacts:
    paths:
      - public

