# Node docker image on which this would be run
image: node:10

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy_production

run tests:
  stage: test
  script:
    - npm install
    - npm run test

deploy to heroku:
  image: ruby:latest
  stage: deploy_production
  only:
    - master
    - main
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY